name: try-gmt
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - gmt=6.5.0
  - pygmt=0.19.0
  - geopandas=1.1.4
  - jupyter-offlinenotebook
  - pip
  - pip:
    - zipp
  
# zipp
